# Generated by Django 2.2.3 on 2019-07-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='normal', max_length=30)),
            ],
            options={
                'db_table': 'social',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True)),
                ('name', models.CharField(max_length=50)),
                ('poassword', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('social_login_id', models.CharField(max_length=100, null=True)),
                ('level', models.CharField(default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social', models.ForeignKey(default=None, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Social')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logined_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
