# Generated by Django 2.2.3 on 2019-07-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='poassword',
            new_name='password',
        ),
    ]
