# Generated by Django 2.2.2 on 2019-07-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190719_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_reader',
            new_name='is_leader',
        ),
    ]
