# Generated by Django 2.2.2 on 2019-07-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190719_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gungu',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
