# Generated by Django 2.2.2 on 2019-07-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190722_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_leader',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
