# Generated by Django 2.2.3 on 2019-07-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190722_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='kakao_nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
