# Generated by Django 2.2.3 on 2019-07-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_employee_kakao_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='kakao_nickname',
        ),
    ]
