# Generated by Django 2.2.3 on 2019-07-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.IntegerField(max_length=3)),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gungu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gungu_code', models.IntegerField(max_length=5)),
                ('gungu_name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.City')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('fax_number', models.CharField(max_length=20)),
                ('opened_at', models.CharField(max_length=8)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=13)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=13)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.City')),
                ('gungu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Gungu')),
            ],
        ),
    ]
