# Generated by Django 2.2.2 on 2019-07-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Gungu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.City')),
            ],
            options={
                'db_table': 'gungu',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=2500, null=True)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('fax_number', models.CharField(max_length=20)),
                ('opened_at', models.CharField(max_length=8)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=13)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=13)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.City')),
                ('gungu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Gungu')),
            ],
            options={
                'db_table': 'store',
            },
        ),
    ]
