# Generated by Django 2.2.2 on 2019-07-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gungu',
            name='gungu_code',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
