# Generated by Django 2.2.2 on 2019-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190716_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gungu',
            name='gungu_code',
            field=models.IntegerField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gungu',
            name='gungu_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
