# Generated by Django 2.2.2 on 2019-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190716_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='gungu',
            name='gungu_code',
            field=models.CharField(max_length=5),
        ),
    ]
