# Generated by Django 2.2.2 on 2019-07-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190716_1706'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='gungu',
            table='gungu',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
    ]
