# Generated by Django 2.2.2 on 2019-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='img_url',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
