# Generated by Django 2.2.2 on 2019-07-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Categories')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=450)),
                ('only_ice', models.BooleanField(default=True)),
                ('oz_price', models.IntegerField(blank=True, default=0, null=True)),
                ('short_price', models.IntegerField(blank=True, default=0, null=True)),
                ('tall_price', models.IntegerField(blank=True, default=0, null=True)),
                ('grande_price', models.IntegerField(blank=True, default=0, null=True)),
                ('venti_price', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('condition', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('volume', models.CharField(max_length=4)),
                ('option', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Categories')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductType')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Section')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=450)),
                ('description', models.CharField(max_length=400, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'db_table': 'hot',
            },
        ),
    ]
