# Generated by Django 2.2.2 on 2019-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
