# Generated by Django 2.2.2 on 2019-07-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='hot',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductType'),
        ),
    ]
